name: wallet_connect_uri_validator
description: Wallet Connect URI validator
version: 0.1.0
repository: https://github.com/SimplioOfficial/wallet-connect-uri-validator.git

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  convert: ^3.1.1
  uuid: ^3.0.7
